database:
  # the name of your JDBC driver
  driverClass: org.postgresql.Driver

  # the username
  user: bookstore

  # the pss
  password: bookstore

  # the JDBC URL
  url: jdbc:postgresql://localhost:5432/bookstore

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  # the maximum amount of time to wait on an empty pool before throwing an exception
  maxWaitForConnection: 1s

  # the SQL query to run when validating a connection's liveness
  validationQuery: "/* Application Health Check */ SELECT 1"

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG